### ISSUE TITLE
Can't find the feature in options.

### ISSUE THREAD

**Issue by abdset** [breiler/Universal-G-Code-Sender#3]
## Problem description 
I downloaded ugs from the link below but can't find joystick check button in options.

### Expected Behavior
Go to Tools - Options - UGS and find Joystick tab. 

### Actual Behavior
Joystick tab is not there.

### Steps to Reproduce the Problem
Download from provided link.
Unzip.
Go to bin directory.
Run ugsplatform64.
Click Tools menu.
Click Options sub-menu.
Click UGS button.

### Specifications
Home made machine using arduino uno geniune as controller, flashed with grbl 1.1f.
#### Version
   UGS Platform 2.0 - Nightly Build Mar 24, 2020

#### Operating system
  Windows 10 x64.

#### Platform
  GRBL 1.1f

### Other question
Whitch pin on whitch controller board are you using to jog, i supose it's bluetooth chip probably connected to rx/tx of the controller according to the video but there is something to code to perform sending jog commands, if it's into, let's say arduino, then how could you find enough memory to add some code ?

i'm using ESP32 as arduino extention to perform:
- bluetooth connection.
- jogging with joystick.
- homing.
- reset zero.
- return to zero.
- kill alarm/soft-reset.
I found this way so it does not disturb the arduino at all.

I was looking at source code of UGS to find the correct values for jogging and i found this:
jogging interval = 100 ms + 10 ms for something else whitch explain why jog step is multiplyed by 1.1 at the end (make sens).
The machine is kind of vibrating a bit at jog first steps and if i try to reduce jogging interval value, it work just fine but keep jogging for some milliseconds when i release the joystick.
I tryed to use 0x80 whitch did work fine to stop it at right time but have some troubles with it (sometimes its just making joystick not working anymore), so i decided to remove that.

Good job out there i will follow this because i have been looking for it.
If you need me to test anything for you, i will be more than glad to do so, just keep in mind that i'm not as good as you doing programming (no java knowledge) but i'm able to put any formula to my esp32 code or physicly test on my machine.

Best regards.

**Comment by breiler** [comment]
You need to build UGS yourself to try out the joystick implementation and you must use the branch: https://github.com/breiler/Universal-G-Code-Sender/tree/feature/joystick

If you wait for a couple of days it should be merged upstream to Winders repository which will automatically be built.

As long as the joystick can be recognised by the operating system it should be detected automatically by UGS. No extra changes to your controller or any extra hardware should be needed. UGS will read the analog or digital value of your gamepad/joystick and translate it to a GCode command which will be sent to GRBL (should also work with g2core, but haven't tested this):
https://github.com/breiler/Universal-G-Code-Sender/blob/feature/joystick/ugs-platform/ugs-platform-plugin-joystick/src/main/java/com/willwinder/ugs/nbp/joystick/service/JoystickJogService.java

**Comment by abdset** [comment]
Smart way to add joystick feature so we can use any kind of joystick we want.
Thank you for your efforts, i'll apreciate to have it.
I will wait till its merged.
Thanks a lot.

**Comment by breiler** [comment]
Now available in the nightly build

**Comment by abdset** [comment]
Thank you.
Here is a video of my machine and how i use the joystick if you are interrested:
https://www.youtube.com/watch?v=-ZjlfELfzZ4
Now i will try joystick feature on nightly build UGS.
